version: '3'

services:

  so-rabbit:
    image: rabbitmq:3.9.15-management-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_PORT=5671
    ports:
      - '15671:15671'
    expose:
      - '5671'

  so-parking:
    build: $PWD/saga-orchestration-example/parking
    restart: unless-stopped
    entrypoint: ['/bin/sh','-c']
    command:
      - |
        /code/wait-for-it.sh -t 0 so-rabbit:5671
        /code/start_dev.sh
    volumes:
      - $PWD/saga-orchestration-example/parking:/code
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=sqlite:////code/parking_db.sqlite3
      - RABBITMQ_BROKER_URL=amqp://guest:guest@so-rabbit:5671
    depends_on:
      - so-rabbit

  so-booking:
    build: $PWD/saga-orchestration-example/booking
    restart: unless-stopped
    entrypoint: ['/bin/sh','-c']
    command:
      - |
        /code/wait-for-it.sh -t 0 so-rabbit:5671
        /code/wait-for-it.sh -t 0 so-parking:8000
        /code/start_dev.sh
    volumes:
      - $PWD/saga-orchestration-example/booking:/code
    ports:
      - '8001:8000'
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=sqlite:////code/booking_db.sqlite3
      - RABBITMQ_BROKER_URL=amqp://guest:guest@so-rabbit:5671
    depends_on:
      - so-rabbit
      - so-parking

  so-billing:
    build: $PWD/saga-orchestration-example/billing
    restart: unless-stopped
    entrypoint: ['/bin/sh','-c']
    command:
      - |
        /code/wait-for-it.sh -t 0 so-rabbit:5671
        /code/wait-for-it.sh -t 0 so-booking:8000
        /code/start_dev.sh
    volumes:
      - $PWD/saga-orchestration-example/billing:/code
    ports:
      - '8002:8000'
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=sqlite:////code/billing_db.sqlite3
      - RABBITMQ_BROKER_URL=amqp://guest:guest@so-rabbit:5671
    depends_on:
      - so-rabbit
      - so-booking
