version: '3'

services:

  es-event-store-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $PWD/event-sourcing-example/postgres/event-store-db/data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  es-read-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $PWD/event-sourcing-example/postgres/read-db/data:/var/lib/postgresql/data
      - $PWD/event-sourcing-example/db_init_scripts/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - '5435:5432'

  es-rabbit:
    image: rabbitmq:3.9.15-management-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_PORT=5671
    ports:
      - '15671:15671'
    expose:
      - '5671'

  es-booking:
    build: $PWD/event-sourcing-example/booking
    restart: unless-stopped
    entrypoint: ['/bin/sh','-c']
    command:
      - |
        /code/wait-for-it.sh -t 0 es-event-store-db:5432
        /code/wait-for-it.sh -t 0 es-read-db:5432
        /code/wait-for-it.sh -t 0 es-rabbit:5671
        /code/start_dev.sh
    volumes:
      - $PWD/event-sourcing-example/booking:/code
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - EVENT_STORE_DATABASE_URL=postgresql://postgres:postgres@es-event-store-db:5432/postgres
      - READ_DATABASE_URL=postgresql://booking_read_user:postgres@es-read-db:5432/postgres
      - RABBITMQ_BROKER_URL=amqp://guest:guest@es-rabbit:5671
      - PERSISTENCE_MODULE=eventsourcing.postgres
      - POSTGRES_DBNAME=postgres
      - POSTGRES_HOST=es-event-store-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - es-event-store-db
      - es-read-db
      - es-rabbit
