version: '3'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  booking:
    build: ./booking
    restart: unless-stopped
    command: /code/start_dev.sh
    volumes:
      - ./booking:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
