version: '3'

services:

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  booking:
    build: $PWD/booking
    restart: unless-stopped
    command: /code/start_dev.sh
    volumes:
      - $PWD/booking:/code
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=8d0b13922dd9fb
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass 8d0b13922dd9fb --loglevel warning
    volumes:
      - $PWD/redis-data:/data
    environment:
     - REDIS_REPLICATION_MODE=master
